name: Build LaTeX and Convert to HTML

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile LaTeX to PDF using Docker
      run: |
        docker run --rm -i --user="$(id -u):$(id -g)" -v "$PWD":/data blang/latex:ctanfull latexmk -pdf main.tex

    - name: Convert PDF to HTML using pdf2htmlEX Docker
      run: |
        docker run --rm -v "$PWD":/pdf bwits/pdf2htmlex pdf2htmlEX --zoom 1.3 main.pdf

    - name: Setup git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        git add -f main.html
        git commit -m "Add generated HTML" || echo "No changes to commit"
        git push origin HEAD:main
