name: Build LaTeX document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX using Docker
      run: |
        docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull latexmk -pdf main.tex

    - name: Push PDF to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add updated_notes.pdf
        git commit -m "Add generated PDF" -a
        git push
